## numpy 套件

In [1]:
a_list=[1,2,3,4,5]  #宣告串列
print(a_list*3)  

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
#numpy套件的ndarray型態，提供element-wise的操作
import numpy as np
a_ndarray=np.array([1,2,3,4,5])
print(a_ndarray*3) #將a_ndarray串列中的值乘上3

[ 3  6  9 12 15]


In [3]:
print(type(a_ndarray))  
print(a_ndarray.ndim) #ndarray的維度
print(a_ndarray.shape) #ndarray的shape
print(a_ndarray.dtype) #ndarray的資料類型

<class 'numpy.ndarray'>
1
(5,)
int32


In [4]:
print(np.zeros(6))  # 六個元素均為零的 1d array
print(np.zeros((2, 6))) # 十二個元素均為零的 2d array
print(np.empty((2, 6, 2))) # 二十四個元素均為未初始化的值
print(np.arange(11)) # 十一個元素為 0 到 10 的 1d array

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[6.23042070e-307 3.56043053e-307]
  [1.60219306e-306 7.56571288e-307]
  [1.89146896e-307 1.37961302e-306]
  [1.05699242e-307 8.01097889e-307]
  [1.78020169e-306 7.56601165e-307]
  [1.02359984e-306 1.33510679e-306]]

 [[2.22522597e-306 1.33511018e-306]
  [6.23057689e-307 1.86921279e-306]
  [8.90098127e-307 1.78020848e-306]
  [1.60219035e-306 1.42418172e-306]
  [2.04712906e-306 1.00132653e-307]
  [8.90111708e-307 2.10077583e-312]]]
[ 0  1  2  3  4  5  6  7  8  9 10]


## ndarray的進階操作

In [5]:
my_array = np.arange(10) #宣告10個元素
print(my_array) 
print(my_array[0])
print(my_array[0:5]) 

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [6]:
#二維ndarray取值
my_2d_array = np.array([np.arange(0, 5), np.arange(5, 10)])
print(my_2d_array)
print(my_2d_array[1, :]) 
print(my_2d_array[:, 1]) 
print(my_2d_array[1, 1]) # 第二列第二欄的元素

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [7]:
#假設有六個組別"Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"，
#其參加人數分別為56, 8, 19, 14, 6, 71人
ironmen = [56, 8, 19, 14, 6, 71]  
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen_array = np.array(ironmen)
groups_array = np.array(groups)
print(ironmen_array)#
print(groups_array) 

[56  8 19 14  6 71]
['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']


In [8]:
# 用人數去篩選組別
print(ironmen_array >= 10) # 布林值陣列
print(groups_array[ironmen_array >= 10]) # 鐵人數大於 10 的組別
# 用組別去篩選人數
print(groups_array != "自我挑戰組") # 布林值陣列
print(ironmen_array[groups_array != "自我挑戰組"]) # 除了自我挑戰組以外的鐵人數

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


## Ndarray轉置

In [11]:
my_1d_array = np.arange(10)  #宣告10個元素
print(my_1d_array) 
my_2d_array = my_1d_array.reshape((2, 5)) #更改array的外型
print(my_2d_array)
print(my_2d_array.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [12]:
print(np.arange(24).reshape(4,6))#印出24個元素，4列*6行

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## ndarray nan(空值) 與 inf(無窮大)

In [13]:
nan_array = np.array([56, 8, 19, 14, 6, np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


In [14]:
normal_samples = np.random.normal(size = 10) 
# 生成 10 組標準常態分配（平均值為 0，標準差為 1 的常態分配）隨機變數
uniform_samples = np.random.uniform(size = 10) 
# 生成 10 組介於 0 與 1 之間均勻分配隨機變數

print(normal_samples)
print("---") 
print(uniform_samples)

[-2.39597116  0.26732782  0.86307853  0.29951624  0.84709317 -0.44122797
 -0.39473886 -0.74646657  0.06501884  0.67882333]
---
[0.69660615 0.52317718 0.20874566 0.17076752 0.54280628 0.85086416
 0.273885   0.77133527 0.41345044 0.96511942]
